### PR TITLE
Adds SPM Support

### PR DESCRIPTION
**Pull request by alexbartisro**
Added support for Swift Package Manager to be used as a dependency for Keyboard Avoiding SPM

### CODE REVIEW

**Comment by anton-plebanovich** [comment]
Hi @trusk89  and thanks for the contribution! Please let me some time to check how SPM works and I'll merge it shortly after

**Comment by alexbartisro** [comment]
Sounds good!

**Comment by anton-plebanovich** [comment]
@trusk89 let me some more time to fix `KeyboardAvoidingView` also because the Obj-c loader can't be used in SPM I need to load `ViewState` manually in `KeyboardAvoidingView`

**Comment by alexbartisro** [comment]
Yeah, I was just looking over this. Sure, take your time!

**Comment by anton-plebanovich** [comment]
`KeyboardAvoidingView (5.1.0)` is released please check if it works for you

**Comment by alexbartisro** [comment]
@anton-plebanovich looks and works great, thanks for the support!

**Pull request merged**
